// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqmdttzrmhqsiwvkfqya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbWR0dHpybWhxc2l3dmtmcXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTcwNTMsImV4cCI6MjA3NDI5MzA1M30.5kG3hwKvK2kaaSj7pow8n7u7y2qJNYmtQy3zIdlHZys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});